name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03
        options: >-
          --privileged
          -p 5000:5000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t misyukevich/pyapp .

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 misyukevich/pyapp

      - name: Push Docker image
        run: |
          docker push misyukevich/pyapp

      - name: Notify Slack about success
        if: success()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook-type: 'incoming-webhook'  # или 'webhook-trigger'
          token: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: '{"text": ":white_check_mark: Build successful!", "attachments": [{"color": "good"}]}'
    
      - name: Notify Slack about failure
        if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook-type: 'incoming-webhook'  # или 'webhook-trigger'
          token: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: '{"text": ":x: Build failed!", "attachments": [{"color": "danger"}]}'
